### ISSUE TITLE
Add clang-tidy github workflow

### ISSUE THREAD

**Issue by aneshlya** [ispc/ispc#3005]
Add clang-tidy check with the following configuration:
```
Checks: '-*, bugprone-*, cert-*, clang-analyzer-*, cppcoreguidelines-*, hicpp-*, misc-*, modernize-*, readability-*,'

CheckOptions:
  - key: readability-function-cognitive-complexity.Threshold
    value: 15
  - key: readability-function-cognitive-complexity.DescribeBasicIncrements
    value: false
  - key: readability-function-size.LineThreshold
    value: 100
  - key: readability-function-size.StatementThreshold
    value: 50

FormatStyle: 'none'
```
